#!/usr/bin/env bash

set -e

ROOT="$(dirname "$0")"
BUILD="$ROOT/build"
CONTENT="$BUILD/content"

_cargo() {
    RUST_BACKTRACE=1 CARGO_TARGET_DIR="$BUILD/target" cargo $1 \
        --manifest-path "$ROOT/server/Cargo.toml" "${@:2}"
}

content-cp() {
    mkdir -p "$CONTENT"
    cp "client/"*".html" "client/"*".css" "$CONTENT/"
}

content() {
    content-cp
    tsc --outDir "$CONTENT/" --lib "es2016,dom" "$ROOT/client/"*".ts"
}

serve() {
    _cargo run "$CONTENT/" "$BUILD/data" 3333
}

test() {
    _cargo test
}

testnocap() {
    _cargo test -- --nocapture
}

func="$1"
if [ "$func" == "" ]; then
    echo "Usage: run <operation>"
elif [ "$(type -t "$func")" == "function" ]; then
    $func
else
    >&2 echo "\"$func\" is not a supported operation."
fi
